{
  "units": "millimeters",
  "sketches": {
    "sketch_1": {
      "name": "sketch_1",
      "location": "/sketches/sketch_1"
    },
    "sketch_2": {
      "name": "sketch_2",
      "location": "/sketches/sketch_2"
    }
  },
  "features": {
    "feature_1": {
      "type": "extrude",
      "name": "extrude_1",
      "distance": 10.0,
      "direction": [ 0.0, 0.0, 1.0]
    },
    "feature_2": {
      "type": "extrude",
      "name": "extrude_2",
      "distance": 10.0,
      "direction": [ 0.0, 1.0, 1.0]
    },
    "feature_3": {
      "type": "combine",
      "name": "combine_1",
      "solid_1": "extrude_1",
      "solid_2": "extrude_2",
      "union": true,
      "intersect": false,
      "cut": false
    },
    "feature_4": {
      "type": "combine",
      "name": "combine_2",
      "solid_1": "extrude_1",
      "solid_2": "extrude_2",
      "union": false,
      "intersect": true,
      "cut": false
    }
  }
}
